
language: generic

# Install Hugo
install:
  # - url=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}')
  - url=https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.deb
  - echo $url
  - curl -OLkSs $url
  - sudo dpkg -i hugo*.deb
  - ls themes

script:
  - npm install
  - npm run build:prod
  - echo 'betterflutter.com' > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  on:
    branch: master